---
vector_name: "vector"
vector_version: "0.20.0"
vector_package: "vector-{{ vector_version }}-1.x86_64"
# vector_url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
vector_url: "https://packages.timber.io/vector/{{ vector_version }}/{{ vector_package }}.rpm"

vector_path: "/tmp/{{ vector_name }}"
vector_bin: "/usr/bin"
vector_config_path: "/etc/{{ vector_name }}"

vector_data_dir: "/var/lib/{{ vector_name }}"

vector_config_template: "templates/vector_config.j2"
vector_service_template: "templates/vector_service.j2"

