stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "hello:gitlab-$CI_COMMIT_SHORT_SHA"

builder:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .
  except:
    - main

deployer:
  stage: deploy
  script:
    - docker build -t $CI_REGISTRY/$IMAGE_NAME .
    - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/$IMAGE_NAME
  only:
    - main
