apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: netology-role-binding
  namespace: lesson2-4
subjects:
- kind: User
  name: netology
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: netology-role
  apiGroup: rbac.authorization.k8s.io
