# https://yandex.cloud/ru/docs/managed-kubernetes/operations/volumes/s3-csi-integration
---
apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
stringData:
  accessKeyID: "YCAJEA6z_FArRuJ2TeOl3ZHMX"
  secretAccessKey: "YCNM_bm-xN1Wnn5Pkntszl3m3aJTdKFPsEzCPgS8"
  endpoint: https://storage.yandexcloud.net


#<идентификатор_ключа_доступа> и <секретный_ключ>
#в terraform/backend.secret.tfvars
#
#access_key = "YCAJEA6z_FArRuJ2TeOl3ZHMX"
#secret_key = "YCNM_bm-xN1Wnn5Pkntszl3m3aJTdKFPsEzCPgS8"
#
# Шифровать ключи не надо, кубернетис сам выполнит шифрование

