apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: nginx-multitool-lbl
  ports:
    - name: port-nginx-svc
      protocol: TCP
      port: {{ .Values.nginx.servicePort }}
      targetPort: port-nginx
    - name: port-multitool-svc
      protocol: TCP
      port: {{ .Values.multitool.servicePort }}
      targetPort: port-multitool
  type: ClusterIP
