---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.43.255
      ansible_user: centos

vector:
  hosts:
    vector-01:
      ansible_host: 158.160.38.240
      ansible_user: centos

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 158.160.36.12
      ansible_user: centos
